version: '3.8'

services:
  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: paz_animal_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_admin_password
      POSTGRES_DB: paz_animal_local
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - paz_animal_network

  # Interfaz de Administración Gráfica pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: paz_animal_pgadmin_gui
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pazanimal.org
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    networks:
      - paz_animal_network

networks:
  paz_animal_network:
    driver: bridge